### ISSUE TITLE
Upravit tlačítko zpět, aby vedlo na stránku ze které uživatel přišel fallback homepage

### ISSUE THREAD

**Issue by Petrnemec98** [Petrnemec98/havlicekdavid#6]

**Comment by wnccz** [comment]
to je trochu komplikovaná úloha. Zvlášť s tím fallbackem.

Jedna z možností je

 <a href="#" onclick="history.go(-1)">Zpět</a>

jenže to se chová identicky jako tlačítko Zpět v prohlížeči. Je otázka jestli v tom je pak přidaná hodnota suplovat na stránce funkci prohlížeče. Dala by se udělat nějaká sofistifikovanější funkce v rámci JS, která zamezí krok zpět mimo situ (abysme neposlali uživatele zpět například do vyhledávače) a tam nastavit ten fallback.

Pak je možné sledovat historii v rámci aplikace (v session proměnných) a nastavit tam nějaký pokročilejší podmínky v rámci PHP. Ale tam zase bude problém v případě, kdy bude uživatel prohlížet web souběžně ve více tabech. 

No takže je to potřeba spíš promyslet tak, aby to tlačítko mělo nějaký hlubší smysl, než tlačítko zpět v browseru.

**Comment by Petrnemec98** [comment]
No spíš tady chybí popis a trochu bad nadpis: 

Upravit zpět šipku tak aby: 
-> Pokud půjdeš na detail projektu z HP, tak poslat na HP 
-> Pokud půjdeš na detail projektu ze všech projektů, tak poslat na všechny projekty 
-> Pokud direct na detail projektu na tak na všechny projekty
-> Všechny projekty vždy na HP 

-> Pokud z about me na všechny projekty, tak zpět na about me 
-> Pokud z about me na detail projektu, tak zpět na about me 
-> Odkudkoliv na about me -> na stejnou stránku 

Pamatovat si pouze poslední krok, aby se zbytek tlačítek choval stejně...

**Comment by wnccz** [comment]
To by se dalo udělat přes [HTTP referrer](https://doc.nette.org/cs/http/request#toc-getreferer)

**Comment by wnccz** [comment]
Co takhle? Je to správně?
![image](https://user-images.githubusercontent.com/890649/230114497-23139e52-801f-472f-8476-df9711fd462e.png)

**Comment by wnccz** [comment]
Vyřešeno v commitu a07efcd
